version: "3"
services:
  server_backend:
    container_name: backend_module
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: mariadb+mariadbconnector://root:lkdawd+2dawpd20@db:3306
      USERNAME: root
      MYSQL_ROOT_PASSWORD: lkdawd+2dawpd20
    volumes:
      - ./static:/static
    ports:
      - "3117:3117"
    depends_on:
      - db

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lkdawd+2dawpd20
    ports:
      - "3306:3306"
    volumes:
      - ./static/database/mysql:/var/lib/mysql